### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [10]:
# Esempio 1 - quadrati dei numeri da 1 a 5

quadrati = []

for i in range(1, 6):
    quadrati.append(i ** 2)

print(quadrati)

quadrati_comp = [i ** 2 for i in range(1, 6)]

print(quadrati_comp)

# Esempio 2 - numeri pari da 0 a 10

pari = []

for i in range(11):
    if i % 2 == 0:
        pari.append(i)

print(pari)

pari_comp = [i for i in range(11) if i % 2 == 0]

print(pari_comp)

# Esempio 3 - doppio dei numeri da 1 a 5

doppi = []

for i in range(1, 6):
    doppi.append(i * 2)

print(doppi)

doppi_comp = [i * 2 for i in range(1, 6)]

print(doppi_comp)

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [11]:
import numpy as np

# 1. Creo il vettore con i numeri primi tra 0 e 10
primi = np.array([2, 3, 5, 7])

print(primi)

# 2. Numero di elementi con len() e .size
print(len(primi))
print(primi.size)

# Essendo un vettore composto da numeri interi mi aspetto un tipo int64 o int32

# 3. Tipo di dato
print(primi.dtype)

# 4. Vettore con i numeri primi usando una list comprehension
primi = np.array([
    n for n in range(2, 11)
    if all(n % i != 0 for i in range(2, n))
])

print(primi)

[2 3 5 7]
4
4
int64
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [12]:
import numpy as np

# Creo l'array 1D
a = np.arange(1, 11)

print(a)

# Creo l'array con la sottostringa di a
b = a[3:9]

print(b)

# Creo l'array reverse di a
c = a[::-1]

print(c)

# Divido 
divisione = a / c

print(divisione)

# Faccio la stessa cosa con le liste
a_lista = list(range(1, 11))

b_lista = a_lista[2:6]
c_lista = a_lista[::-1]

divisione_lista = []

for i in range(len(a_lista)):
    divisione_lista.append(a_lista[i] / c_lista[i])

print(a_lista)
print(b_lista)
print(c_lista)
print(divisione_lista)



[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]
[ 0.1         0.22222222  0.375       0.57142857  0.83333333  1.2
  1.75        2.66666667  4.5        10.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3, 4, 5, 6]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.1, 0.2222222222222222, 0.375, 0.5714285714285714, 0.8333333333333334, 1.2, 1.75, 2.6666666666666665, 4.5, 10.0]
